/********************************************************************
* QplotDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error QplotDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableQplotDict();
extern void G__cpp_setup_inheritanceQplotDict();
extern void G__cpp_setup_typetableQplotDict();
extern void G__cpp_setup_memvarQplotDict();
extern void G__cpp_setup_globalQplotDict();
extern void G__cpp_setup_memfuncQplotDict();
extern void G__cpp_setup_funcQplotDict();
extern void G__set_cpp_environmentQplotDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Qplot_Gui.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__QplotDictLN_TClass;
extern G__linked_taginfo G__QplotDictLN_TBuffer;
extern G__linked_taginfo G__QplotDictLN_TMemberInspector;
extern G__linked_taginfo G__QplotDictLN_TObject;
extern G__linked_taginfo G__QplotDictLN_string;
extern G__linked_taginfo G__QplotDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__QplotDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__QplotDictLN_TList;
extern G__linked_taginfo G__QplotDictLN_TObjArray;
extern G__linked_taginfo G__QplotDictLN_TQObject;
extern G__linked_taginfo G__QplotDictLN_TGWindow;
extern G__linked_taginfo G__QplotDictLN_TGObject;
extern G__linked_taginfo G__QplotDictLN_TGFrame;
extern G__linked_taginfo G__QplotDictLN_TGCompositeFrame;
extern G__linked_taginfo G__QplotDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__QplotDictLN_TGMainFrame;
extern G__linked_taginfo G__QplotDictLN_TGMenuBar;
extern G__linked_taginfo G__QplotDictLN_TGDockableFrame;
extern G__linked_taginfo G__QplotDictLN_TGListBox;
extern G__linked_taginfo G__QplotDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__QplotDictLN_TGFileInfo;
extern G__linked_taginfo G__QplotDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__QplotDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__QplotDictLN_TKey;
extern G__linked_taginfo G__QplotDictLN_TDirectoryFile;
extern G__linked_taginfo G__QplotDictLN_TTree;
extern G__linked_taginfo G__QplotDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__QplotDictLN_MyMainFrame;

/* STUB derived class for protected member access */
